name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deploy files
      id: deploy
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
      with:
        flags: '-avzr --delete'
        src: './'
        dest: 'vadim@wp-server.ru:/www/lustshop/www/test'

    - name: Display status from deploy
      run: echo "${{ steps.deploy.outputs.status }}"v
